### ISSUE TITLE
cannot open source file "../Common/Common.h"

### ISSUE THREAD

**Issue by hdnshare** [ivanhawkes/fbxtool#1]
Dear Ivan,

Thanks for the tool, but at: https://github.com/ivanhawkes/fbxtool/blob/df6584b274cc55f23b4ca602dd45c9cba65073ca/fbxtool/Common.cxx#L12
Should it be like this instead?
`#include "Common.h"`

Also I see that you are using VS 2017 & FBX tool 2018.1.1, I think you should tell the user that in case they don't know how to setup.
In my case, I'm using VS 2015, I go to Project property's General and set:
Target Platform Version = 8.1
Platform Toolset = Visual Studio 2015 (v140)
About FBX tool, I install FBX SDK 2017.0.1 and go to VC++ Directories to edit a bit.

Thanks,
HDN

**Comment by ivanhawkes** [comment]
Thanks for the feedback. I've updated the README, and set the project to work with VS 2015, since it doesn't need anything new from VS 2017.
